### ISSUE TITLE
japanese localization doesn't produce sentences

### ISSUE THREAD

**Issue by romk1n** [vadymmarkov/Fakery#45]
I have the following code 

```
let fakery = Faker(locale: "ja")
let sentence = fakery.lorem.sentence(wordsAmount: random() % 100)
```

but the result is 

```
(lldb) p sentence
(String?) $R0 = "  ."
```

any idea?
Thanks.

**Comment by vadymmarkov** [comment]
@romk1n Hi, sorry for my supper late reply. It happens because [japanese localisation](https://github.com/vadymmarkov/Fakery/blob/master/Resources/Locales/ja.json) has less data comparing for example to english. To generate sentences it needs to have "lorem" dictionary like in https://github.com/vadymmarkov/Fakery/blob/master/Resources/Locales/en.json#L4744. Feel free to contribute if you feel like it's something you'd like to do.
