### ISSUE TITLE
SwiftyJSON depency

### ISSUE THREAD

**Issue by d3pwnd** [vadymmarkov/Fakery#51]
SwiftyJSON decency is not pointing to any specific release, though due to the new SwiftyJSON Release (Support for Swift 3.0) my project (Swift2.2) can't use Fakery anymore.

Should be fixed with replacing ` s.dependency 'SwiftyJSON', '< 3.0.0'` to pod-spec.

**Comment by fuxx** [comment]
Same for me.

**Comment by vadymmarkov** [comment]
@d3pwnd @fuxx I'm planning to do Swift 3 migration during next week, so it will be fixed there.

**Comment by fuxx** [comment]
Hi @vadymmarkov thanks for the quick reply. We didnt meant Swift 3 :)
We have to stick to Swift 2.2 for some weeks as Facebook and some other dependencies are not yet ready for Swift 3. Unfortunately you did not specify a version for SwiftyJSON in your dependencies. 

Because of that the latest version is being used which is already lifted to Swift 3. The problem now is, that we need a pod update from you were the SwiftyJSON version is hardwired to Swift 2.2. 

Only other option right now is to mirror the project to a private pod repo and maintain it on our own, but anyway for the future a hardwired version number of SwiftyJSON would be good as on future upgrades like Swift 4 we would have the same problems again.

**Comment by vadymmarkov** [comment]
@fuxx @d3pwnd I've made 1.3.2 release with specified `SwiftyJSON` version is Podspec 😉

**Comment by fuxx** [comment]
Great, works flawless. Thanks for the effort!

**Comment by d3pwnd** [comment]
Thx for the quick response, i appreciate is.

**Comment by vadymmarkov** [comment]
I'm closing this one. Also `Fakery` doesn't have any dependencies anymore from the last release 1.4.0.
